### ISSUE TITLE
pass USB

### ISSUE THREAD

**Issue by segator** [ich777/docker-debian-buster#1]
HI your docker is awesome, just playing with GPU passtru to VM's and find out your docker,
i'm wondering is there is a way to pass USB's like mouse and keyboard

**Comment by ich777** [comment]
This should be possible since I've also got a container running where I pass through a USB device connected via a serial interface /dev/ttyUSB0.
I do this with the command: '--device=/dev/ttyUSB0:/dev/ttyUSB0' at the docker extra startup parameters.

If this is also achievable with a HID like a mouse and keyboard I can't tell but I will look into it, if you got any success in the meantime please let me know.

**Comment by segator** [comment]
tried to pass ttyUSB0 doesnt work :( 
the docker boots fine but keyboard neither mouse is not there

**Comment by ich777** [comment]
That won't work unless you have the path '/dev/ttyUSB0' in your system.
You have to find the right path to your USB device and then pass it through but no garantuee that is that easy...
I will look into it when I got time for this. ;)

EDIT: This was just an example what I did to pass through a USB device.

**Comment by segator** [comment]
HI @ich777  thanks for your answers 👍 

you are right I dont have dev ttyUSB0, how can I identify the device path? is there any command I can use?

**Comment by ich777** [comment]
This should answer you question partially: [Click](https://linuxhint.com/list-usb-devices-linux/)
